spring.application.name=Prestamo-y-mantenimiento-de-equipos-audiovisuales




# Conexión a Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.iowpypfwegsgrbytzgoa
spring.datasource.password=Bc1071328927
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect